version: "2.4"
services:
  converter:
    build: .
    ports:
      - "${ServerIP}:8181:8080/tcp"
    volumes:
      # Config files
      - generated-news:/output
    restart: unless-stopped
    env_file:
      - .env

volumes:
  generated-news:
