version: "2.4"
services:
  converter:
    build: .
    ports:
      - "${FTK_SERVER_PORT}:${FTK_SERVER_PORT}/tcp"
    volumes:
      # Config files
      - generated-news:/output
    restart: unless-stopped
    env_file:
      - .env

volumes:
  generated-news:
